spring.application.name=loan-service

spring.datasource.url=jdbc:postgresql://localhost:5442/loans_db
spring.datasource.username=solaris
spring.datasource.password=solaris123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.repair-on-migrate=true
spring.flyway.validate-on-migrate=false
logging.level.org.flywaydb=INFO

server.port=8088

internal.secret=${INTERNAL_SECRET:changeme-dev-only}

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=when_authorized
management.endpoint.prometheus.access=unrestricted
management.metrics.tags.application=${spring.application.name}

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}
