spring.application.name=document-service

spring.datasource.url=jdbc:postgresql://localhost:5446/documents_db
spring.datasource.username=solaris
spring.datasource.password=solaris123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.repair-on-migrate=true
spring.flyway.validate-on-migrate=false
logging.level.org.flywaydb=INFO

server.port=8092

internal.secret=${INTERNAL_SECRET:changeme-dev-only}
account.service.url=${ACCOUNT_SERVICE_URL:http://localhost:8082}
auth.service.url=${AUTH_SERVICE_URL:http://localhost:8081}

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=when_authorized
management.endpoint.prometheus.access=unrestricted
management.metrics.tags.application=${spring.application.name}

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}
