spring.application.name=account-service

spring.datasource.url=jdbc:postgresql://localhost:5434/accounts_db
spring.datasource.username=solaris
spring.datasource.password=solaris123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082
