spring.application.name=account-service

spring.datasource.url=jdbc:postgresql://localhost:5434/accounts_db
spring.datasource.username=solaris
spring.datasource.password=solaris123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=account-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Allow large payloads for KYC document uploads (base64 images)
server.tomcat.max-http-form-post-size=15MB
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# Actuator & Prometheus
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=when_authorized
management.endpoint.prometheus.access=unrestricted
management.metrics.tags.application=${spring.application.name}
