services:
  postgres-auth:
    image: postgres:16
    container_name: postgres-auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: solaris
      POSTGRES_PASSWORD: solaris123
    ports:
      - "5433:5432"

  postgres-accounts:
    image: postgres:16
    container_name: postgres-accounts
    environment:
      POSTGRES_DB: accounts_db
      POSTGRES_USER: solaris
      POSTGRES_PASSWORD: solaris123
    ports:
      - "5434:5432"